version: '3.7'

services:
  bert:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python3 main.py
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - private

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      - private

networks:
  private:
    driver: overlay
  traefik-proxy:
    external: true

volumes:
  postgres_data:
  static_volume:
  media_volume: